apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ankitdechart-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://ankit20000/charts
    chart: ankitchart
    targetRevision: 0.1.0
    helm:
      # Only override specific values here
      values: |
        replicaCount: 2 
        image:
          repository: nginx  

  destination:
    server: https://kubernetes.default.svc
    namespace: default  # Change the namespace where the app will be deployed

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
